package:
  name: q2-ms
  version: {{ PLUGIN_VERSION }}

source:
  path: ..

build:
  script: make install

requirements:
  host:
    - python {{ python }}
    - setuptools
    - versioningit
    - wheel

  build:
    - setuptools
    - versioningit

  run:
    - bioconductor-xcms
    - pymzml
    - qiime2 {{ qiime2_epoch }}.*
    - q2-types {{ qiime2_epoch }}.*
    - q2templates {{ qiime2_epoch }}.*
    - r-base
    - r-devtools

test:
  requires:
    - parameterized
  imports:
    - q2_ms
    - qiime2.plugins.ms
  commands:
    - pytest --pyargs q2_ms

about:
  home: https://github.com/bokulich-lab/q2-ms
  license: BSD-3-Clause
  license_family: BSD
