package:
  name: q2-ms
  version: {{ PLUGIN_VERSION }}

source:
  path: ..

build:
  script: make install

requirements:
  host:
    - python {{ python }}
    - setuptools
    - versioningit
    - wheel

  build:
    - setuptools
    - versioningit

  run:
    - bioconductor-xcms
    - bioconductor-msexperiment
    - pymzml
    - pyteomics
    - qiime2 >={{ qiime2 }}
    - q2-types >={{ q2_types }}
    - q2templates >={{ q2templates }}
    - r-base
    - r-msio
    - r-optparse
test:
  requires:
    - parameterized
  imports:
    - q2_ms
    - qiime2.plugins.ms
  commands:
    - pytest --pyargs q2_ms

about:
  home: https://github.com/bokulich-lab/q2-ms
  license: BSD-3-Clause
  license_family: BSD
